server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name www.rapid-is.co.uk;
    root /var/www/rapid-is/system/nginx-root;

    ssl_certificate /etc/letsencrypt/www.rapid-is.co.uk/fullchain.cer;
    ssl_certificate_key /etc/letsencrypt/www.rapid-is.co.uk/www.rapid-is.co.uk.key;
    include /etc/nginx/snippets/ssl-params.conf;

    #
    # DEMO PLATFORM
    #

    location = /demo {
        return 301 https://demo.rapid-is.co.uk/;
    }

    location /demo/ {
        rewrite ^/demo/(.*)$ https://demo.rapid-is.co.uk/$1 permanent;
    }

    #
    # SUPPORT SYSTEM
    #

    location = /support {
        return 301 https://support.rapid-is.co.uk/;
    }

    location /support/ {
        rewrite ^/support/(.*)$ https://support.rapid-is.co.uk/$1 permanent;
    }

    #
    # EVERYTHING ELSE
    #

    location / {
        return 301 https://rapid-is.co.uk$request_uri;
    }

    location ~ /.well-known {
        allow all;
    }

    client_max_body_size 1g;
}